import React, { useState } from 'react';
import { ChevronDown, HelpCircle } from 'lucide-react';

const faqs = [
  {
    q: 'Is BillBook AI a real offline GST invoice software?',
    a: 'Yes. BillBook AI is a fully offline GST invoicing software that runs inside your web browser. Once loaded, you can disconnect from the internet and continue creating invoices, managing clients, and tracking expenses without any cloud dependency. Your data is stored locally on your device.',
  },
  {
    q: 'Is this a free GST billing tool for small businesses?',
    a: 'BillBook AI is not free, but it costs just ₹299 — a one-time payment. There are no monthly fees, no per-invoice charges, and no hidden costs. For most small businesses and freelancers in India, that’s less than one month of any SaaS subscription, and you keep the tool for life.',
  },
  {
    q: 'Is BillBook AI a true alternative to Zoho Books with a one-time payment?',
    a: 'Yes. If you primarily need GST-compliant invoicing, client management, expense tracking and PDF exports, BillBook AI is a one-time-payment alternative to Zoho Books, QuickBooks and Tally. It is purpose-built for Indian small businesses, freelancers and consultants who don’t need enterprise accounting features.',
  },
  {
    q: 'How does the private AI receipt scanner work?',
    a: 'The AI receipt scanner uses Tesseract.js — a powerful OCR engine — that runs entirely in your browser. When you upload a receipt image, the AI extracts the vendor name, amount and date locally on your device. No image is ever uploaded to any server, making it a 100% private AI receipt scanner.',
  },
  {
    q: 'Will it work without internet, and on what devices?',
    a: 'After the first load, BillBook AI works fully offline on any modern browser — Chrome, Edge, Firefox, Safari — on Windows, macOS, Linux, Android and iPhone. As long as your browser supports local storage and JavaScript (every modern browser does), you’re good to go.',
  },
  {
    q: 'What happens to my data if I change devices?',
    a: 'BillBook AI includes a one-click Data Backup module. You can export your entire business data as a single JSON file, move it to a new device, and import it back. Your data is always portable and always under your control.',
  },
  {
    q: 'Are the invoices GST-compliant for India?',
    a: 'Yes. Invoices generated by BillBook AI include GSTIN, HSN/SAC codes, CGST + SGST + IGST breakdown, place of supply, taxable value and total — everything required for a GST-compliant tax invoice under Indian GST rules.',
  },
  {
    q: 'Do you offer refunds?',
    a: 'Yes. We honor a 7-day no-questions-asked refund window via Gumroad. If BillBook AI doesn’t work for your business, we’ll refund you in full.',
  },
];

export default function FAQ() {
  const [openIdx, setOpenIdx] = useState(0);

  return (
    <section id="faq" className="py-16 lg:py-24 bg-white">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-blue-50 border border-blue-100 text-blue-700 text-xs font-semibold mb-4">
            <HelpCircle className="w-3.5 h-3.5" />
            Frequently Asked Questions
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-slate-900 tracking-tight">
            Got questions? <span className="bb-gradient-text">We’ve got answers.</span>
          </h2>
          <p className="mt-4 text-lg text-slate-600">
            Everything you need to know about BillBook AI — the offline GST invoicing tool for Indian businesses.
          </p>
        </div>

        <div className="space-y-3" data-testid="faq-list">
          {faqs.map((f, i) => {
            const open = openIdx === i;
            return (
              <div
                key={f.q}
                className={`rounded-xl border transition-all ${
                  open
                    ? 'border-blue-200 bg-blue-50/40 shadow-sm'
                    : 'border-slate-200 bg-white hover:border-slate-300'
                }`}
                data-testid={`faq-item-${i}`}
              >
                <button
                  type="button"
                  className="w-full flex items-center justify-between gap-4 px-5 py-4 text-left"
                  onClick={() => setOpenIdx(open ? -1 : i)}
                  aria-expanded={open}
                >
                  <span className="text-base font-semibold text-slate-900">{f.q}</span>
                  <ChevronDown
                    className={`w-5 h-5 shrink-0 text-blue-600 transition-transform ${
                      open ? 'rotate-180' : ''
                    }`}
                  />
                </button>
                <div
                  className={`grid transition-all duration-300 ease-out ${
                    open ? 'grid-rows-[1fr] opacity-100' : 'grid-rows-[0fr] opacity-0'
                  }`}
                >
                  <div className="overflow-hidden">
                    <p className="px-5 pb-5 text-slate-600 leading-relaxed text-sm sm:text-base">{f.a}</p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
